[package]
name = "cmd20"
version = "0.2.0"
authors = ["tomowatt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
clap = "2.27.0"
