name: Lint

on: [ push ]

permissions:
  contents: read

jobs:
  lint:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - uses: super-linter/super-linter@v7.1.0  
      name: Super-Linter
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
