name: Lint

on: [ push ]

jobs:
  lint:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: github/super-linter@v5.1.0
      name: Super-Linter
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
